[tools]
# Tools
pnpm = "10.25.0"
"npm:prettier" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"

# LSPs
"github:luals/lua-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"

# Languages
go = "1.25.5"
node = "25.2.1"

[tool_alias]
pnpm = "npm:pnpm"
