git:
    overrideGpg: true
    pagers:
        - colorArg: always
          pager: delta --dark --paging=never
gui:
    showRandomTip: false
    nerdFontsVersion: "3"
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip' | 'quit'
os:
    editPreset: nvim
promptToReturnFromSubprocess: false
